# Generated by Django 3.2 on 2022-10-28 04:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('fruit', 'Fruits'), ('vegetable', 'Verduras'), ('flower', 'Flores')], max_length=10)),
                ('createdDate', models.DateField()),
                ('price', models.PositiveSmallIntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
                ('stock', models.PositiveSmallIntegerField(verbose_name=django.core.validators.MinValueValidator(1))),
            ],
        ),
    ]
